export const REGISTER_CAT_INFO = '[REGISTER] REDISTER_CAT_INFO';
export const SET_CAT_PICTURE = '[UPDATE] SET_CAT_PICTURE';
export const UPDATE_CURRENT_CAT_INFO = '[UPDATE] UPDATE_CURRENT_CAT_INFO';
export const RESET_FIELDS = '[RESET] RESET_FIELDS';
