export const UPDATE_USER_INFO = '[UPDATE] UPDATE_USER_INFO';
export const IDENTIFY_USER_INFO = '[IDENTIFY] IDENTIFY_USER_INFO';
export const IDENTIFY_SET_USER_PROFILEPICTURE = '[IDENTIFY] IDENTIFY_SET_USER_PROFILEPICTURE';

export const REGISTER_CAT_INFO = '[REGISTER] REGISTER_CAT_INFO';
export const RESET_FIELDS_USER = '[LOGOUT] RESET_FIELDS_USER';
